var dataSet = [
    ["करत हूँ पुकार आज सुनिये गुहार", "Karat Hoon Pukar Aaj Suniye Guhar","सार बचन छंद बंद, भाग 2", "Sar Bachan Poetry, Part-2", "33", "3", "सुबह उठने के बाद, नियमावली", "After waking up in morning, Niyamawali", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Karat Hoon Pukar Aaj Suniye Guhar.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Karat Hoon Pukar Aaj Suniye Guhar.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Karat Hoon Pukar Aaj Suniye Guhar.mp4'>Video</a>" ],




    ["गुरु मैं गुनहगार अति भारी", "Guru Main Gunahagar Ati Bhari","सार बचन छंद बंद, भाग 2", "Sar Bachan Poetry, Part-2", "29", "3", "रात को सोने से पहले, नियमावली", "Before retiring to bed in evening, Niyamawali", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Main Gunahagar Ati Bhari.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Main Gunahagar Ati Bhari.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Main Gunahagar Ati Bhari.mp4'>Video</a>" ],




     ["भोग धरे राधास्वामी आगे", "Bhog Dhare Radhasoami Aage","सार बचन छंद बंद, भाग 2", "Sar Bachan Poetry, Part-2", "42", "4", "भोग", "Bhog", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Bhog Dhare Radhasoami Aage.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Bhog Dhare Radhasoami Aage.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Bhog Dhare Radhasoami Aage.mp4'>Video</a>" ],

     ["भाव भक्ति से बिंजन करती", "Bhav Bhakti Se Binjan Karti","सार बचन छंद बंद, भाग 2", "Sar Bachan Chand Band Part 2", "", "", "भोग, नियमावली", "Bhog, Niyamawali", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Bhav Bhakti Se Binjan Karti.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Bhav Bhakti Se Binjan Karti.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Bhav Bhakti Se Binjan Karti.mp4'>Video</a>" ],


    
     ["चेतो मेरे प्यारे तेरे भले की कहूँ", "Cheto Mere Pyare Tere Bhale Ki Kahoon","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "19", "1", "दैनिक", "Daily", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Cheto Mere Pyare Tere Bhale Ki Kahoon.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Cheto Mere Pyare Tere Bhale Ki Kahoon.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Cheto Mere Pyare Tere Bhale Ki Kahoon.mp4'>Video</a>" ],





     ["अहो मेरे सतगुरु अहो मेरी जान", "Aho Mere Satguru Aho Meri Jan","प्रेम बानी, भाग 4", "Prem Bani, Part - 4", "39", "", "रविवार", "Sunday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Aho Mere Satguru Aho Meri Jan.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Aho Mere Satguru Aho Meri Jan.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Aho Mere Satguru Aho Meri Jan.mp4'>Video</a>" ],

     ["गुरु की मौज रहो तुम धार", "Guru Ki Mauj Raho Tum Dhar","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "18", "8", "रविवार", "Sunday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Ki Mauj Raho Tum Dhar.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Ki Mauj Raho Tum Dhar.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Ki Mauj Raho Tum Dhar.mp4'>Video</a>" ],

     ["मौत से डरत रहो दिन रात", "Maut Se Darat Raho Din Rat","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "15", "6", "रविवार", "Sunday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Maut Se Darat Raho Din Rat.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Maut Se Darat Raho Din Rat.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Maut Se Darat Raho Din Rat.mp4'>Video</a>" ],




     ["गुरु चरण पकड़ दृढ़ भाई", "Guru Charan Pakad Dradh Bhai","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "18", "4", "सोमवार", "Monday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Charan Pakad Dradh Bhai.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Charan Pakad Dradh Bhai.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Charan Pakad Dradh Bhai.mp4'>Video</a>" ],

     ["गुरु ध्यान धरो तुम मन में", "Guru Dhyan Dharo Tum Man Mein","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "18", "3", "सोमवार", "Monday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Dhyan Dharo Tum Man Mein.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Dhyan Dharo Tum Man Mein.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Dhyan Dharo Tum Man Mein.mp4'>Video</a>" ],

     ["नाम दान अब सतगुरु दीजे", "Naam Dan Ab Satguru Dije","सार बचन छंद बंद, भाग 2", "Sar Bachan Poetry, Part-2", "33", "6", "सोमवार", "Monday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Naam Dan Ab Satguru Dije.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Naam Dan Ab Satguru Dije.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Naam Dan Ab Satguru Dije.mp4'>Video</a>" ],




    ["आज खेले सुरत गुरु चरनन पास", "Aaj Khele Surat Guru Charnan Pas","प्रेम बानी, भाग 2", "Prem Bani, Part - 2", "12", "36", "मंगलवार", "Tuesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Aaj Khele Surat Guru Charnan Pas.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Aaj Khele Surat Guru Charnan Pas.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Aaj Khele Surat Guru Charnan Pas.mp4'>Video</a>" ],

    ["मन रे क्यों गुमान अब करना", "Man Re Kyon Guman Ab Karna","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "15", "15", "मंगलवार", "Tuesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Man Re Kyon Guman Ab Karna.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Man Re Kyon Guman Ab Karna.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Man Re Kyon Guman Ab Karna.mp4'>Video</a>" ],

    ["मोहिं मिला सुहाग गुरु का", "Mohin Mila Suhag Guru Ka","सार बचन छंद बंद, भाग 2", "Sar Bachan Poetry, Part-2", "28", "3", "मंगलवार", "Tuesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Mohin Mila Suhag Guru Ka.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Mohin Mila Suhag Guru Ka.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Mohin Mila Suhag Guru Ka.mp4'>Video</a>" ],

     ["सतगुरु का नाम पुकारो", "Satguru Ka Naam Pukaro","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "18", "5", "मंगलवार", "Tuesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Satguru Ka Naam Pukaro.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Satguru Ka Naam Pukaro.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Satguru Ka Naam Pukaro.mp4'>Video</a>" ],


    
     ["आज चलो बिदेसन अपने देश", "Aaj Chalo Bidesan Apne Desh","प्रेम बानी, भाग 2", "Prem Bani, Part - 2", "12", "3", "बुधवार", "Wednesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Aaj Chalo Bidesan Apne Desh.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Aaj Chalo Bidesan Apne Desh.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Aaj Chalo Bidesan Apne Desh.mp4'>Video</a>" ],

      ["गुरु का ध्यान कर प्यारे", "Guru Ka Dhyan Kar Pyare","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "19", "2", "बुधवार", "Wednesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Ka Dhyan Kar Pyare.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Ka Dhyan Kar Pyare.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Ka Dhyan Kar Pyare.mp4'>Video</a>" ],

     ["मेरे धूम भई अति भारी दरस राधास्वामी कीन्हा रे", "Mere Dhoom Bhai Ati Bhari Daras Radhasoami Kinha Re","प्रेम बानी, भाग 3", "Prem Bani, Part - 3", "21", "2", "बुधवार", "Wednesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Mere Dhoom Bhai Ati Bhari Daras Radhasoami Kinha Re.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Mere Dhoom Bhai Ati Bhari Daras Radhasoami Kinha Re.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Mere Dhoom Bhai Ati Bhari Daras Radhasoami Kinha Re.mp4'>Video</a>" ],

     ["मेरे हिये में बजत बधाई संत सँग पाया रे", "Mere Hiye Mein Bajat Badhaee Sant Sang Paya Re","प्रेम बानी, भाग 3", "Prem Bani, Part - 3", "21", "1", "बुधवार", "Wednesday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Mere Hiye Mein Bajat Badhaee Sant Sang Paya Re.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Mere Hiye Mein Bajat Badhaee Sant Sang Paya Re.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Mere Hiye Mein Bajat Badhaee Sant Sang Paya Re.mp4'>Video</a>" ],





     ["गुरु धरा सीस पर हाथ मन क्यों सोच करे", "Guru Dhara Sis Par Hath Man Kyon Soch Kare","प्रेम बानी, भाग 3", "Prem Bani, Part - 3", "35", "3", "गुरुवार", "Thursday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Dhara Sis Par Hath Man Kyon Soch Kare.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Dhara Sis Par Hath Man Kyon Soch Kare.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Dhara Sis Par Hath Man Kyon Soch Kare.mp4'>Video</a>" ],

     ["आज पकड़ो गुरु के चरन सम्हार", "Aaj Pakado Guru Ke Charan Samhar","प्रेम बानी, भाग 2", "Prem Bani, Part - 2", "12", "9", "गुरुवार", "Thursday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Aaj Pakado Guru Ke Charan Samhar.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Aaj Pakado Guru Ke Charan Samhar.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Aaj Pakado Guru Ke Charan Samhar.mp4'>Video</a>" ],

      ["धाम अपने चलो भाई", "Dham Apne Chalo Bhai","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "19", "18", "गुरुवार", "Thursday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Dham Apne Chalo Bhai.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Dham Apne Chalo Bhai.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Dham Apne Chalo Bhai.mp4'>Video</a>" ],

       ["प्रेम दात गुरु दीजिये मेरे समरथ दाता हो", "Prem Dat Guru Dijiye Mere Samrath Data Ho","प्रेम बानी, भाग 4", "Prem Bani, Part - 4", "40", "60", "गुरुवार", "Thursday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Prem Dat Guru Dijiye Mere Samrath Data Ho.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Prem Dat Guru Dijiye Mere Samrath Data Ho.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Prem Dat Guru Dijiye Mere Samrath Data Ho.mp4'>Video</a>" ],

       ["मैं हुई सखी अपने प्यारे की प्यारी", "Main Hui Sakhi Apne Pyare Ki Pyari","प्रेम बानी, भाग 3", "Prem Bani, Part - 3", "24", "3", "गुरुवार", "Thursday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Main Hui Sakhi Apne Pyare Ki Pyari.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Main Hui Sakhi Apne Pyare Ki Pyari.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Main Hui Sakhi Apne Pyare Ki Pyari.mp4'>Video</a>" ],



        ["क्यों सोच करे मन मूरख", "Kyon Soch Kare Man Moorakh","प्रेम बानी, भाग 4", "Prem Bani, Part - 4", "40", "6", "शुक्रवार", "Friday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Kyon Soch Kare Man Moorakh.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Kyon Soch Kare Man Moorakh.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Kyon Soch Kare Man Moorakh.mp4'>Video</a>" ],

        ["दरश दे आज बँधाओ धीर", "Darash De Aaj Bandhao Dheer","प्रेम बानी, भाग 1", "Prem Bani, Part - 1", "5", "6", "शुक्रवार", "Friday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Darash De Aaj Bandhao Dheer.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Darash De Aaj Bandhao Dheer.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Darash De Aaj Bandhao Dheer.mp4'>Video</a>" ],

        ["मित्र तेरा कोई नहीं संगियन में", "Mitr Tera Koi Nahin Sangiyan Mein","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "15", "5", "शुक्रवार", "Friday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Mitr Tera Koi Nahin Sangiyan Mein.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Mitr Tera Koi Nahin Sangiyan Mein.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Mitr Tera Koi Nahin Sangiyan Mein.mp4'>Video</a>" ],

        ["सुरत आज मगन भई", "Surat Aaj Magan Bhai","सार बचन छंद बंद, भाग 2", "Sar Bachan Poetry, Part-2", "35", "26", "शुक्रवार", "Friday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Surat Aaj Magan Bhai.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Surat Aaj Magan Bhai.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Surat Aaj Magan Bhai.mp4'>Video</a>" ],

        ["जब से मैं देखा राधास्वामी का मुखड़ा", "Jab Se Main Dekha Radhasoami Ka Mukhada","प्रेम बानी, भाग 3", "Prem Bani, Part - 3", "24", "4", "शुक्रवार", "Friday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Jab Se Main Dekha Radhasoami Ka Mukhada.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Jab Se Main Dekha Radhasoami Ka Mukhada.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Jab Se Main Dekha Radhasoami Ka Mukhada.mp4'>Video</a>" ],




         ["गुरु तारेंगे हम जानी", "Guru Tarenge Ham Jani","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "19", "15", "शनिवार","Saturday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Guru Tarenge Ham Jani.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Guru Tarenge Ham Jani.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Guru Tarenge Ham Jani.mp4'>Video</a>" ],

         ["यहाँ तुम समझ सोच कर चलना", "Yehan Tum Samajh Soch Kar Chalna","सार बचन छंद बंद, भाग 1", "Sar Bachan Poetry, Part-1", "15", "14", "शनिवार","Saturday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Yehan Tum Samajh Soch Kar Chalna.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Yehan Tum Samajh Soch Kar Chalna.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Yehan Tum Samajh Soch Kar Chalna.mp4'>Video</a>" ],

         ["सुरतिया यांच रही गुरु चरन प्रेम की दात", "Suratiya Yanch Rahi Guru Charan Prem Ki Dat","प्रेम बानी, भाग 2", "Prem Bani, Part - 2", "11", "33", "शनिवार","Saturday", "<table class='audioColumnDataTable'><tr><td><a href='https://www.radhasoamifaith.org/Audio/Shabd/Suratiya Yanch Rahi Guru Charan Prem Ki Dat.mp3' style='cursor:pointer;' data-toggle='tooltip' title='Download' download=''><span class='glyphicon glyphicon-save' style='font-size:15px;'></span></a></td><td><audio class='sankalanaudio' controlslist='nodownload' controls='controls'><source src='https://www.radhasoamifaith.org/Audio/Shabd/Suratiya Yanch Rahi Guru Charan Prem Ki Dat.mp3' type='audio/mp3'></audio></td></tr></table>", "<a href='https://www.radhasoamifaith.org/Video/Poetry/Aaj Pakado Guru Ke Charan Samhar.mp4'>Video</a>" ]
 ];